target 'ZLSwipeableViewSwiftDemo' do
	pod 'UIColor+FlatColors'
	pod 'Cartography'
	# pod 'ReactiveUI'
end

target 'ZLSwipeableViewSwiftDemoTests' do
	pod 'UIColor+FlatColors'
	pod 'Cartography'
	# pod 'ReactiveUI'
end

use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['Cartography'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4'
      end
    end
  end
end
